[package]
name = "slack_event"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros"] }
